name: CI/CD for Spring Boot with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          cd frontend/webservice
          npm install

      - name: Build Project
        run: |
          cd frontend/webservice
          npm run build

      - name: Archive Production Artifacts
        run: |
          tar -czf deploy.tar.gz frontend/webservice/build/ target/*.jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packaged-application
          path: deploy.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packaged-application
          path: target/

      - name: Setup key
        id: setup-key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem

      - name: Copy Archive to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          source: "target/deploy.tar.gz"
          target: "/home/ubuntu/deployment/"

#      - name: Copy Frontend to EC2
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ubuntu
#          key: ${{ secrets.DEPLOY_KEY }}
#          source: "frontend/webservice/build"
#          target: "/home/ubuntu/deployment/"

      - name: Extract Archive on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/ubuntu/deployment
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz

      - name: Connect SSH and Restart Services
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@${{ secrets.DEPLOY_HOST }} '
            sudo systemctl restart demo &&
            sudo systemctl restart nginx
          '